### ISSUE TITLE
Web page show postgres commands

### ISSUE THREAD

**Issue by rpelissi** [individual-it/bandwidthd-pSQL-frontend#3]
Hi,
I have tried to install the php fles on separate apache server (centos 7) after installing php and psql modules. Still, it seems that when I access the bandwidth web pages, it does not execute the command but instead display them. Any ideas on this?
![bandwidthd](https://cloud.githubusercontent.com/assets/385483/7102322/3e7522d2-e04a-11e4-802a-04cc32b23423.png)
See screenshot attached.

Thanks

**Comment by rpelissi** [comment]
Found the issue:
In /etc/php.ini
Locate the ligne
short_open_tag
it should be under the 
;;;;;;;;;;;;;;;;;;;;
; php.ini Options  ;
;;;;;;;;;;;;;;;;;;;;

and be set to:
short_open_tag = On

after that
systemctl restart httpd

And it works!

**Comment by wagnst** [comment]
i have replaced the developer short tags in pull request #5
